# Generated by Django 2.2.2 on 2019-07-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('application_id', models.CharField(max_length=400)),
                ('secret_token', models.CharField(max_length=400)),
                ('app_type', models.CharField(choices=[('gitlab', 'Gitlab')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
