# Generated by Django 2.2.2 on 2019-07-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
