# Generated by Django 2.2.2 on 2019-07-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190712_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_access_token',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
