# Generated by Django 2.2.2 on 2019-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_application_admin_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
