# Generated by Django 2.2.2 on 2019-07-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secret_token',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_token',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
