# Generated by Django 2.2.2 on 2019-07-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_application_url'),
        ('user', '0003_auto_20190711_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_application', to='app.Application'),
            preserve_default=False,
        ),
    ]
