# Generated by Django 2.2.2 on 2019-07-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_application', to='app.Application'),
        ),
    ]
