# Generated by Django 2.2.2 on 2019-07-12 06:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190711_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='app_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
